name: Backend Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  api-gateway:
    name: Build API Gateway
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api-gateway

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - run: mvn clean verify

  music-service:
    name: Build Music Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: music-service

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - run: mvn clean verify

  rec-service:
    name: Build Recommendation Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rec-service

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - run: mvn clean verify
